enum ActionTypes {
    FETCH_INGREDIENTS = 'FETCH_INGREDIENTS',
    SET_INGREDIENT_DETAILS = 'SET_INGREDIENT_DETAILS',
    DELETE_INGREDIENT_DETAILS = 'DELETE_INGREDIENT_DETAILS',
    SET_ORDER_NUMBER = 'SET_ORDER_NUMBER',
    ADD_INGREDIENT = 'ADD_INGREDIENT',
    DELETE_INGREDIENT = 'DELETE_INGREDIENT',
    MOVE_INGREDIENT = 'MOVE_INGREDIENT',
    CLEAR_CONSTRUCTOR = 'CLEAR_CONSTRUCTOR',
    REGISTER_USER = 'REGISTER_USER',
    LOGIN_USER = 'LOGIN_USER',
    LOGOUT_USER = 'LOGOUT_USER',
    CHECK_TOKEN = 'CHECK_TOKEN',
  }
  
export default ActionTypes;
  